name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push and Build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: |
            ptrfrll/nv-docker-trex:latest
            ptrfrll/nv-docker-trex:cuda10
      - name: Push and Build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.cuda11
          tags: |
            ptrfrll/nv-docker-trex:cuda11