name: Publish Docker image
on:
  push:
    branches: ghcr
jobs:
  cuda-11:
    name: Push CUDA 11 image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/ptrfrll/nv-docker-trex
          tags: |
            type=ref,event=tag
          flavor: |
            latest=true
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push and Build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: test
  cuda-10:
    name: Push CUDA 10 image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/ptrfrll/nv-docker-trex
          tags: |
            type=ref,event=tag
            type=raw,value=latest
          flavor: |
            latest=false
            prefix=cuda10-
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push and Build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.cuda10
          tags: ${{ steps.meta.outputs.tags }}
