name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  cuda-11:
    name: Push CUDA 11 image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ptrfrll/nv-docker-trex
          tags: |
            type=ref,event=tag
          flavor: |
            latest=true
            prefix=cuda11-
      - name: Show tags
        run: |
          echo ${{ steps.meta.outputs.tags }}
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push and Build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: |
            ptrfrll/nv-docker-trex:latest
            ptrfrll/nv-docker-trex:cuda11
  cuda-10:
    name: Push CUDA 10 image to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ptrfrll/nv-docker-trex
          tags: |
            type=ref,event=tag
          flavor: |
            latest=false
            prefix=cuda10-
      - name: Show tags
        run: |
          echo ${{ steps.meta.outputs.tags }}
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push and Build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile.cuda10
          tags: |
            ptrfrll/nv-docker-trex:cuda10
